#!/bin/bash
# =============================================================================
# Flutter Play Store CI/CD - Auto Apply Script
# =============================================================================
# This script applies the generated configuration to the Flutter project.
# Usage: bash apply.sh [config_json_file]
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE} Flutter Play Store CI/CD Auto Apply${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# Check if we're in a Flutter project
if [ ! -f "pubspec.yaml" ]; then
    echo -e "${RED}Error: This is not a Flutter project directory${NC}"
    echo "Please run this script from your Flutter project root."
    exit 1
fi

# Create necessary directories
echo -e "${YELLOW}[1/5] Creating directories...${NC}"
mkdir -p android/app/keystore
mkdir -p android/fastlane
mkdir -p android/fastlane/metadata/android/ko-KR/changelogs
echo -e "${GREEN}  Created: android/app/keystore/${NC}"
echo -e "${GREEN}  Created: android/fastlane/${NC}"
echo -e "${GREEN}  Created: android/fastlane/metadata/android/ko-KR/changelogs/${NC}"

# Detect gradle type
echo -e "${YELLOW}[2/5] Detecting Gradle configuration...${NC}"
if [ -f "android/app/build.gradle.kts" ]; then
    GRADLE_FILE="android/app/build.gradle.kts"
    GRADLE_TYPE="kts"
    echo -e "${GREEN}  Detected: Kotlin DSL (build.gradle.kts)${NC}"
elif [ -f "android/app/build.gradle" ]; then
    GRADLE_FILE="android/app/build.gradle"
    GRADLE_TYPE="groovy"
    echo -e "${GREEN}  Detected: Groovy DSL (build.gradle)${NC}"
else
    echo -e "${RED}Error: Cannot find build.gradle file${NC}"
    exit 1
fi

# Create Fastfile.playstore if not exists
echo -e "${YELLOW}[3/5] Creating Fastlane configuration...${NC}"
if [ ! -f "android/fastlane/Fastfile.playstore" ]; then
    # Get applicationId from build.gradle
    if [ "$GRADLE_TYPE" = "kts" ]; then
        APP_ID=$(grep -E "applicationId\s*=" "$GRADLE_FILE" | head -1 | sed 's/.*"\(.*\)".*/\1/')
    else
        APP_ID=$(grep -E "applicationId\s" "$GRADLE_FILE" | head -1 | sed 's/.*"\(.*\)".*/\1/')
    fi

    cat > android/fastlane/Fastfile.playstore << EOF
# Fastfile for Play Store Internal Testing Deployment
# Path: android/fastlane/Fastfile.playstore
# Generated by Flutter Play Store CI/CD Helper

default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :deploy_internal do
    # Environment variables
    aab_path = ENV["AAB_PATH"] || "../build/app/outputs/bundle/release/app-release.aab"
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    puts "========================================="
    puts "Deploying to Play Store Internal Testing"
    puts "========================================="
    puts "AAB Path: #{aab_path}"
    puts "Service Account: #{json_key}"
    puts ""

    # Verify AAB exists
    unless File.exist?(aab_path)
      UI.user_error!("AAB file not found: #{aab_path}")
    end

    # Verify Service Account exists
    unless File.exist?(json_key)
      UI.user_error!("Service Account JSON not found: #{json_key}")
    end

    # Upload to Play Store
    upload_to_play_store(
      package_name: "${APP_ID}",
      track: "internal",
      aab: aab_path,
      json_key: json_key,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )

    puts ""
    puts "========================================="
    puts "Successfully deployed to Internal Testing!"
    puts "========================================="
  end

  desc "Validate Service Account JSON"
  lane :validate do
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    validate_play_store_json_key(
      json_key: json_key
    )

    puts "Service Account validation successful!"
  end

  desc "Promote internal to beta"
  lane :promote_to_beta do
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    upload_to_play_store(
      package_name: "${APP_ID}",
      track: "internal",
      track_promote_to: "beta",
      json_key: json_key,
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

    puts "Promoted from internal to beta!"
  end
end
EOF
    echo -e "${GREEN}  Created: android/fastlane/Fastfile.playstore${NC}"
else
    echo -e "${YELLOW}  Skipped: android/fastlane/Fastfile.playstore already exists${NC}"
fi

# Create key.properties template
echo -e "${YELLOW}[4/5] Creating key.properties template...${NC}"
if [ ! -f "android/key.properties" ]; then
    cat > android/key.properties << 'EOF'
# Release Keystore Configuration
# WARNING: Do not commit this file to version control!
# Add 'android/key.properties' to your .gitignore

storeFile=app/keystore/key.jks
storePassword=YOUR_STORE_PASSWORD
keyAlias=YOUR_KEY_ALIAS
keyPassword=YOUR_KEY_PASSWORD
EOF
    echo -e "${GREEN}  Created: android/key.properties (template)${NC}"
    echo -e "${YELLOW}  NOTE: Please update with your actual keystore credentials${NC}"
else
    echo -e "${YELLOW}  Skipped: android/key.properties already exists${NC}"
fi

# Update .gitignore
echo -e "${YELLOW}[5/5] Updating .gitignore...${NC}"
GITIGNORE_ENTRIES=(
    "android/key.properties"
    "android/app/keystore/"
    "*.jks"
    "*.keystore"
)

for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qF "$entry" .gitignore 2>/dev/null; then
        echo "$entry" >> .gitignore
        echo -e "${GREEN}  Added to .gitignore: $entry${NC}"
    fi
done

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN} Setup Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "1. Generate your release keystore:"
echo -e "   ${YELLOW}keytool -genkey -v -keystore android/app/keystore/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias your-key-alias${NC}"
echo ""
echo "2. Update android/key.properties with your keystore credentials"
echo ""
echo "3. Modify android/app/build.gradle.kts to add signing configuration"
echo "   (See the HTML wizard for the exact code)"
echo ""
echo "4. Set up GitHub Secrets:"
echo "   - RELEASE_KEYSTORE_BASE64"
echo "   - RELEASE_KEYSTORE_PASSWORD"
echo "   - RELEASE_KEY_ALIAS"
echo "   - RELEASE_KEY_PASSWORD"
echo "   - GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64"
echo ""
echo -e "${BLUE}For detailed instructions, open:${NC}"
echo "  .github/util/flutter/android-playstore-setup-wizard/index.html"
