# =============================================================================
# Flutter Play Store CI/CD - Auto Apply Script (Windows PowerShell)
# =============================================================================
# This script applies the generated configuration to the Flutter project.
# Usage: powershell -ExecutionPolicy Bypass -File apply.ps1
# =============================================================================

$ErrorActionPreference = "Stop"

Write-Host "=========================================" -ForegroundColor Blue
Write-Host " Flutter Play Store CI/CD Auto Apply" -ForegroundColor Blue
Write-Host "=========================================" -ForegroundColor Blue
Write-Host ""

# Check if we're in a Flutter project
if (-not (Test-Path "pubspec.yaml")) {
    Write-Host "Error: This is not a Flutter project directory" -ForegroundColor Red
    Write-Host "Please run this script from your Flutter project root."
    exit 1
}

# Create necessary directories
Write-Host "[1/5] Creating directories..." -ForegroundColor Yellow
$directories = @(
    "android/app/keystore",
    "android/fastlane",
    "android/fastlane/metadata/android/ko-KR/changelogs"
)

foreach ($dir in $directories) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "  Created: $dir" -ForegroundColor Green
    } else {
        Write-Host "  Exists: $dir" -ForegroundColor Gray
    }
}

# Detect gradle type
Write-Host "[2/5] Detecting Gradle configuration..." -ForegroundColor Yellow
$gradleFile = $null
$gradleType = $null

if (Test-Path "android/app/build.gradle.kts") {
    $gradleFile = "android/app/build.gradle.kts"
    $gradleType = "kts"
    Write-Host "  Detected: Kotlin DSL (build.gradle.kts)" -ForegroundColor Green
} elseif (Test-Path "android/app/build.gradle") {
    $gradleFile = "android/app/build.gradle"
    $gradleType = "groovy"
    Write-Host "  Detected: Groovy DSL (build.gradle)" -ForegroundColor Green
} else {
    Write-Host "Error: Cannot find build.gradle file" -ForegroundColor Red
    exit 1
}

# Get applicationId
$gradleContent = Get-Content $gradleFile -Raw
$appId = ""
if ($gradleContent -match 'applicationId\s*=?\s*"([^"]+)"') {
    $appId = $matches[1]
    Write-Host "  Application ID: $appId" -ForegroundColor Green
}

# Create Fastfile.playstore
Write-Host "[3/5] Creating Fastlane configuration..." -ForegroundColor Yellow
$fastfilePath = "android/fastlane/Fastfile.playstore"

if (-not (Test-Path $fastfilePath)) {
    $fastfileContent = @"
# Fastfile for Play Store Internal Testing Deployment
# Path: android/fastlane/Fastfile.playstore
# Generated by Flutter Play Store CI/CD Helper

default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :deploy_internal do
    # Environment variables
    aab_path = ENV["AAB_PATH"] || "../build/app/outputs/bundle/release/app-release.aab"
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    puts "========================================="
    puts "Deploying to Play Store Internal Testing"
    puts "========================================="
    puts "AAB Path: #{aab_path}"
    puts "Service Account: #{json_key}"
    puts ""

    # Verify AAB exists
    unless File.exist?(aab_path)
      UI.user_error!("AAB file not found: #{aab_path}")
    end

    # Verify Service Account exists
    unless File.exist?(json_key)
      UI.user_error!("Service Account JSON not found: #{json_key}")
    end

    # Upload to Play Store
    upload_to_play_store(
      package_name: "$appId",
      track: "internal",
      aab: aab_path,
      json_key: json_key,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )

    puts ""
    puts "========================================="
    puts "Successfully deployed to Internal Testing!"
    puts "========================================="
  end

  desc "Validate Service Account JSON"
  lane :validate do
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    validate_play_store_json_key(
      json_key: json_key
    )

    puts "Service Account validation successful!"
  end

  desc "Promote internal to beta"
  lane :promote_to_beta do
    json_key = ENV["GOOGLE_PLAY_JSON_KEY"] || "~/.config/gcloud/service-account.json"

    upload_to_play_store(
      package_name: "$appId",
      track: "internal",
      track_promote_to: "beta",
      json_key: json_key,
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

    puts "Promoted from internal to beta!"
  end
end
"@
    Set-Content -Path $fastfilePath -Value $fastfileContent -Encoding UTF8
    Write-Host "  Created: $fastfilePath" -ForegroundColor Green
} else {
    Write-Host "  Skipped: $fastfilePath already exists" -ForegroundColor Yellow
}

# Create key.properties template
Write-Host "[4/5] Creating key.properties template..." -ForegroundColor Yellow
$keyPropertiesPath = "android/key.properties"

if (-not (Test-Path $keyPropertiesPath)) {
    $keyPropertiesContent = @"
# Release Keystore Configuration
# WARNING: Do not commit this file to version control!
# Add 'android/key.properties' to your .gitignore

storeFile=app/keystore/key.jks
storePassword=YOUR_STORE_PASSWORD
keyAlias=YOUR_KEY_ALIAS
keyPassword=YOUR_KEY_PASSWORD
"@
    Set-Content -Path $keyPropertiesPath -Value $keyPropertiesContent -Encoding UTF8
    Write-Host "  Created: $keyPropertiesPath (template)" -ForegroundColor Green
    Write-Host "  NOTE: Please update with your actual keystore credentials" -ForegroundColor Yellow
} else {
    Write-Host "  Skipped: $keyPropertiesPath already exists" -ForegroundColor Yellow
}

# Update .gitignore
Write-Host "[5/5] Updating .gitignore..." -ForegroundColor Yellow
$gitignoreEntries = @(
    "android/key.properties",
    "android/app/keystore/",
    "*.jks",
    "*.keystore"
)

$gitignorePath = ".gitignore"
$gitignoreContent = ""
if (Test-Path $gitignorePath) {
    $gitignoreContent = Get-Content $gitignorePath -Raw
}

foreach ($entry in $gitignoreEntries) {
    if ($gitignoreContent -notmatch [regex]::Escape($entry)) {
        Add-Content -Path $gitignorePath -Value $entry
        Write-Host "  Added to .gitignore: $entry" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Green
Write-Host " Setup Complete!" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Blue
Write-Host "1. Generate your release keystore:"
Write-Host "   keytool -genkey -v -keystore android/app/keystore/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias your-key-alias" -ForegroundColor Yellow
Write-Host ""
Write-Host "2. Update android/key.properties with your keystore credentials"
Write-Host ""
Write-Host "3. Modify android/app/build.gradle.kts to add signing configuration"
Write-Host "   (See the HTML wizard for the exact code)"
Write-Host ""
Write-Host "4. Set up GitHub Secrets:"
Write-Host "   - RELEASE_KEYSTORE_BASE64"
Write-Host "   - RELEASE_KEYSTORE_PASSWORD"
Write-Host "   - RELEASE_KEY_ALIAS"
Write-Host "   - RELEASE_KEY_PASSWORD"
Write-Host "   - GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64"
Write-Host ""
Write-Host "For detailed instructions, open:" -ForegroundColor Blue
Write-Host "  .github/util/flutter/android-playstore-setup-wizard/index.html"
